#!/usr/bin/env python3
"""
Generate high-quality voiceover audio files for 'The Memory Breach' script.
Splits content into separate .wav files for each section.
"""

import os
import torch
import torchaudio as ta
from chatterbox.tts import ChatterboxTTS

# Automatically detect the best available device
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

print(f"Using device: {device}")

# Create output directory
output_dir = "outputs/memory_breach_gero"
VOICE_REFERENCE = "gero_voice_cleaned.wav"  # Gero's cleaned voice
os.makedirs(output_dir, exist_ok=True)

# Load the model
print("Loading Chatterbox TTS model...")
model = ChatterboxTTS.from_pretrained(device=device)

# Define the sections from VoiceOver_TheMemoryBreach.md
# High-quality female voice settings: moderate exaggeration for expressiveness, 
# lower cfg_weight for more deliberate/dramatic pacing
sections = [
    {
        "filename": "memory-breach-section-01-intro.wav",
        "text": "They told us the station was a fortress, a silent watcher at the edge of the known universe. I have walked these corridors for what feels like a thousand cycles, the only living pulse in a tomb of blue neon and cold steel. But lately, the silence has changed. It's no longer empty; it's waiting. In the deep static between my thoughts, I can hear the walls beginning to hum with a history that isn't mine."
    },
    {
        "filename": "memory-breach-section-02-echoes.wav",
        "text": "I see them in the shadows now—echoes of the crew, or perhaps just ghosts generated by a dying drive. A face in the doorway, a figure crouching in the dark, eyes wide with a fear I cannot process. They are fragments of a life we left behind, bleeding through the hull. Suddenly, the smell of ozone is replaced by the phantom scent of pine and dry earth. The mountains are calling to us from across the void, heavy and jagged, demanding to be remembered."
    },
    {
        "filename": "memory-breach-section-03-synthesis.wav",
        "text": "The barrier is failing. The desert sun burns through the titanium plating, and the logic of the machine dissolves into a fever dream. We are no longer just observers drifting in the dark; we are the glitch where the metal meets the memory. The synthesis has begun, and I am no longer sure where the simulation ends and the soul begins."
    }
]

# ULTRA-SLOW CINEMATIC SETTINGS - Maximum drama, female-style delivery
# Very low cfg_weight = extremely slow, deliberate pacing
# High exaggeration = softer, more expressive emotional delivery
cfg_weight = 0.1  # Ultra-slow, dramatic pacing (cinematic narration)
exaggeration = 0.8  # High emotion - softer, more expressive
temperature = 0.9  # Higher variation for natural female-like cadence

generated_files = []

print("\n" + "="*60)
print("Generating voiceover audio files...")
print("="*60)

for i, section in enumerate(sections, 1):
    print(f"\n[{i}/{len(sections)}] Generating: {section['filename']}")
    print(f"    Text: {section['text'][:60]}...")
    
    # Generate the audio
    wav = model.generate(
        section["text"],
        audio_prompt_path=VOICE_REFERENCE,
        cfg_weight=cfg_weight,
        exaggeration=exaggeration,
        temperature=temperature
    )
    
    # Save the audio file
    output_path = os.path.join(output_dir, section["filename"])
    ta.save(output_path, wav, model.sr)
    generated_files.append(section["filename"])
    print(f"    Saved: {output_path}")

print("\n" + "="*60)
print("GENERATION COMPLETE")
print("="*60)
print("\nGenerated files (lowercase, hyphenated format):")
for filename in generated_files:
    print(f"  - {filename}")
print(f"\nOutput directory: {output_dir}")
